### PR TITLE
Add Custom View Support, Misc. changes

### PR DESCRIPTION
**Pull request by ItzNotABug**
Added custom view support which can fix this => #45 
Proper package name formatting (directory naming) => lowercase (`EasyUpiPayment` to `easyupipayment`)
Dependency updates, 
Sample app now uses the new `startPayment(customView)` method.

### CODE REVIEW

**Comment by ItzNotABug** [comment]
The files might look new & a lot of new lines but its just because of the package (directory) name refactoring. :)

**Comment by PatilShreyas** [comment]
Thanks, @ItzNotABug for this PR!

**Comment by ItzNotABug** [comment]
> Thanks, @ItzNotABug for this PR!

Any updates on this?
or something still needs to be added or removed here? 😅

**Comment by PatilShreyas** [comment]
Yeah I'm thinking about something. Will let you know

**Comment by PatilShreyas** [comment]
@ItzNotABug Now after thinking about it I've some valid points to discuss with you.

- Developer should not have provision to set custom view for `PaymentUiActivity`. Because nobody is gonna interact with that custom view. If anybody passed custom view which contain button, text, etc then it won't look good.
- Instead, we can get current style/theme of Activity (Which we are getting in `EasyUpiPayment` class from `Builder`) and then set it to `PaymentUiActivity`. Think on it.
- Please do the package changes revert back so it'll be easy to review me. Once looks good after review then you can fix it again.

**Comment by ItzNotABug** [comment]
> @ItzNotABug Now after thinking about it I've some valid points to discuss with you.
> 
> * Developer should not have provision to set custom view for `PaymentUiActivity`. Because nobody is gonna interact with that custom view. If anybody passed custom view which contain button, text, etc then it won't look good.
> * Instead, we can get current style/theme of Activity (Which we are getting in `EasyUpiPayment` class from `Builder`) and then set it to `PaymentUiActivity`. Think on it.
> * Please do the package changes revert back so it'll be easy to review me. Once looks good after review then you can fix it again.

* I agree for the first point regarding the buttons, texts, etc.
But I still think it will be good to have the ability the use the Customised View.
For example: Using a custom background, or a custom progress view or a loader textview, etc.

* For the second suggestion, I think we can keep that too.
Not sure if its just a bloat over my point suggested above.
Keeping both is obviously not a good thing.

* Will make the required changes to the package name, once we have a common ground on the above points.

**Comment by PatilShreyas** [comment]
@ItzNotABug Any update on this?

**Comment by ItzNotABug** [comment]
> @ItzNotABug Any update on this?

I was waiting for your reply on the comment that I made a while ago.

Maybe if we could decide on something, either point 1 or 2, which to go forward, I could look into it.

**Comment by PatilShreyas** [comment]
Okay, so according to me we shouldn't provide devs with custom views. We could just parse theme from `Activity` and set that in payment UI activity.

**Comment by PatilShreyas** [comment]
Also, please make sure you revert file package name changes so that it'll be easy to review changes.

**Comment by ItzNotABug** [comment]
I added support to use the activity's theme but also added ability to pass a Custom Theme resource.

**Comment by PatilShreyas** [comment]
@ItzNotABug There are some conflicts with the base branch. I can see you changed indentation rules. Please use repository-specific rules.

**Comment by PatilShreyas** [comment]
Please don't make unnecessary changes which are not supposed to be in this PR. We should only do the changes which PR's title suggests

**Comment by ItzNotABug** [comment]
Hey @PatilShreyas,
Sorry I'm not sure what changed the indentations. (maybe I hit reformat code).
Let me know if the latest commit gives what we discussed.

**Comment by PatilShreyas** [comment]
@ItzNotABug still not visible. Can't review PR

**Comment by PatilShreyas** [comment]
Closing it, feel free to reopen

**Pull request closed without merging**
